# Shared host Bash selection for configure and test registration (PS1B-450).
include_guard(GLOBAL)

# TRUE in <out_var> for a bash.exe that starts WSL. Windows hosts only.
function(_psxrecomp_is_wsl_launcher path out_var)
    set(${out_var} FALSE PARENT_SCOPE)
    if(NOT CMAKE_HOST_WIN32)
        return()
    endif()
    file(TO_CMAKE_PATH "${path}" _path)
    string(TOLOWER "${_path}" _path)
    set(_resolved_path "${_path}")
    if(EXISTS "${path}")
        file(REAL_PATH "${path}" _resolved_path)
        string(TOLOWER "${_resolved_path}" _resolved_path)
    endif()
    set(_root "$ENV{SystemRoot}")
    if(NOT _root)
        set(_root "$ENV{windir}")
    endif()
    if(NOT _root)
        set(_root "C:/Windows")
    endif()
    set(_resolved_root "${_root}")
    if(EXISTS "${_root}")
        file(REAL_PATH "${_root}" _resolved_root)
    endif()
    file(TO_CMAKE_PATH "${_root}" _root)
    string(TOLOWER "${_root}" _root)
    string(REGEX REPLACE "/+$" "" _root "${_root}")
    file(TO_CMAKE_PATH "${_resolved_root}" _resolved_root)
    string(TOLOWER "${_resolved_root}" _resolved_root)
    string(REGEX REPLACE "/+$" "" _resolved_root "${_resolved_root}")
    # Check written and resolved locations: an alias may hide a launcher, and
    # a WindowsApps spelling must remain refused even when it points elsewhere.
    foreach(_candidate IN ITEMS "${_path}" "${_resolved_path}")
        if(_candidate MATCHES "/microsoft/windowsapps/[^/]+$")
            set(${out_var} TRUE PARENT_SCOPE)
            return()
        endif()
        foreach(_windows_root IN ITEMS "${_root}" "${_resolved_root}")
            string(FIND "${_candidate}" "${_windows_root}/" _below_root)
            if(_below_root EQUAL 0)
                set(${out_var} TRUE PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endforeach()
endfunction()

# The bash that runs the fingerprint script in <out_var>, or "" when there is
# none. <launcher_var> gets the first WSL launcher that was passed over.
function(psxrecomp_find_bash out_var launcher_var)
    set(${out_var} "" PARENT_SCOPE)
    set(${launcher_var} "" PARENT_SCOPE)
    # An environment override wins over cached/configured discovery on every host.
    if(NOT "$ENV{PSX_GIT_BASH}" STREQUAL "")
        set(_explicit "$ENV{PSX_GIT_BASH}")
        _psxrecomp_is_wsl_launcher("${_explicit}" _is_launcher)
        if(_is_launcher OR NOT EXISTS "${_explicit}" OR IS_DIRECTORY "${_explicit}")
            message(FATAL_ERROR "PSX_GIT_BASH does not name a usable host Bash: ${_explicit}")
        endif()
        set(${out_var} "${_explicit}" PARENT_SCOPE)
        return()
    endif()
    if(NOT CMAKE_HOST_WIN32)
        find_program(_psxrt_bash NAMES bash)
        if(_psxrt_bash)
            set(${out_var} "${_psxrt_bash}" PARENT_SCOPE)
        endif()
        return()
    endif()

    # A bash named by the caller, or kept in the cache by an earlier configure,
    # is used as given. Only a launcher is passed over.
    set(_launcher "")
    if(_psxrt_bash)
        _psxrecomp_is_wsl_launcher("${_psxrt_bash}" _is_launcher)
        if(NOT _is_launcher)
            set(${out_var} "${_psxrt_bash}" PARENT_SCOPE)
            return()
        endif()
        set(_launcher "${_psxrt_bash}")
    endif()
    # Git for Windows in its usual folders.
    set(_candidates "")
    set(_x86 "ProgramFiles(x86)")
    foreach(_base IN ITEMS "$ENV{ProgramFiles}" "$ENV{ProgramW6432}" "$ENV{${_x86}}")
        if(_base)
            file(TO_CMAKE_PATH "${_base}" _base)
            list(APPEND _candidates "${_base}/Git/bin/bash.exe" "${_base}/Git/usr/bin/bash.exe")
        endif()
    endforeach()
    if(NOT "$ENV{LOCALAPPDATA}" STREQUAL "")
        file(TO_CMAKE_PATH "$ENV{LOCALAPPDATA}" _base)
        list(APPEND _candidates "${_base}/Programs/Git/bin/bash.exe"
                                "${_base}/Programs/Git/usr/bin/bash.exe")
    endif()
    # A Git in another folder, through its git.exe on PATH: <Git>/cmd from a
    # Windows shell, <Git>/mingw64/bin from inside Git Bash. Then PATH itself.
    file(TO_CMAKE_PATH "$ENV{PATH}" _path_dirs)
    foreach(_dir IN LISTS _path_dirs)
        if(_dir AND EXISTS "${_dir}/git.exe")
            get_filename_component(_up1 "${_dir}" DIRECTORY)
            get_filename_component(_up2 "${_up1}" DIRECTORY)
            list(APPEND _candidates "${_up1}/bin/bash.exe" "${_up1}/usr/bin/bash.exe"
                                    "${_up2}/bin/bash.exe" "${_up2}/usr/bin/bash.exe")
        endif()
    endforeach()
    foreach(_dir IN LISTS _path_dirs)
        if(_dir)
            list(APPEND _candidates "${_dir}/bash.exe")
        endif()
    endforeach()

    foreach(_candidate IN LISTS _candidates)
        _psxrecomp_is_wsl_launcher("${_candidate}" _is_launcher)
        if(_is_launcher)
            if(NOT _launcher AND EXISTS "${_candidate}")
                set(_launcher "${_candidate}")
            endif()
        elseif(EXISTS "${_candidate}" AND NOT IS_DIRECTORY "${_candidate}")
            set(${out_var} "${_candidate}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${launcher_var} "${_launcher}" PARENT_SCOPE)
endfunction()

