include("${ROOT}/framework_identity.cmake")
file(MAKE_DIRECTORY "${WORK}/runtime")
set(pin "0123456789012345678901234567890123456789")
set(tree "abcdef0123456789abcdef0123456789abcdef01")
file(WRITE "${WORK}/runtime/FRAMEWORK_PIN" "${pin}\n")
file(WRITE "${WORK}/runtime/FRAMEWORK_TREE" "${tree}\n")
psxrecomp_framework_identity("${WORK}" p r s)
psxrecomp_framework_tree("${WORK}" "${p}" t)
if(NOT p STREQUAL pin OR NOT t STREQUAL tree OR NOT s STREQUAL "archive")
    message(FATAL_ERROR "Archive commit/tree identity was lost")
endif()
set(PSX_FRAMEWORK_TREE "1111111111111111111111111111111111111111")
psxrecomp_framework_tree("${WORK}" "${p}" t)
if(NOT t STREQUAL PSX_FRAMEWORK_TREE)
    message(FATAL_ERROR "Explicit tree identity was lost")
endif()
unset(PSX_FRAMEWORK_TREE)
file(WRITE "${WORK}/runtime/FRAMEWORK_TREE" "$Format:%T$\n")
psxrecomp_framework_tree("${WORK}" "" t)
if(NOT t STREQUAL "")
    message(FATAL_ERROR "Unresolved placeholder became an invented identity")
endif()
message(STATUS "PASS tier tree identity archive/caller/unknown")
